services:
  hospital-ui:
    build:
      context: ..
      dockerfile: hospital/ui/Dockerfile
    container_name: hospital-ui
    ports:
      - "3000:80"
    networks:
      - hospital-net

  fhir:
    image: hapiproject/hapi:v8.6.0-1-tomcat
    container_name: hospital-fhir
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/hapi-fhir-db;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
    volumes:
      - ./fhir-data:/data
    networks:
      - hospital-net

networks:
  hospital-net:
    driver: bridge