services:
  hospital-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: hospital-ui
    ports:
      - "3000:80"
    networks:
      - hospital-net

networks:
  hospital-net:
    driver: bridge
