"""add portal user active flag and role cleanup

Revision ID: e908a44528e5
Revises: 704bf8ce8375
Create Date: 2026-03-25 19:57:09.334533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e908a44528e5'
down_revision: Union[str, None] = '704bf8ce8375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portal_users', 'is_active')
    # ### end Alembic commands ###
